20

diff --git a/.github/workflows/vic3-tiger.yml b/.github/workflows/vic3-tiger.yml
--- a/.github/workflows/vic3-tiger.yml
+++ b/.github/workflows/vic3-tiger.yml
@@ -53,15 +53,13 @@ jobs:
     - name: Check if error log is empty
       id: check_error_log
       run: |
-        run: |
-          if [ -s ./error.log ]; then
-            echo "::set-output name=has_errors::true"
-            exit 1
-          else
-            echo "::set-output name=has_errors::false"
-          fi
-    
-          # Block PR unless override is applied
+        if [ -s ./error.log ]; then
+          echo "has_errors=true" >> $GITHUB_OUTPUT
+          exit 1
+        else
+          echo "has_errors=false" >> $GITHUB_OUTPUT
+        fi
+
     - name: Fail PR if there are errors
       if: steps.check_error_log.outputs.has_errors == 'true' && github.event.pull_request.head.ref != 'override-branch'
       run: exit 1
